config/routes.rb
Rails.application.routes.draw do
      get 'welcome/index'
      
      resources :customers do
        resources :orders
      end
      
      resources :orders do
          resources :order_items
      end
      
      post 'find', to: 'customers#find', as: :find
      
  
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    resources :users
    resources :sessions

    root 'welcome#index'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
    
    validates :email, presence: true,
        length: { minimum: 5 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  
   validates :city, presence: true,
                    length: { minimum: 5 }
    validates :street_address, presence: true,
                    length: { minimum: 10 }                    
    validates :state, presence: true,
                    length: { minimum: 2 }
    validates :postal_code, presence: true,
                    length: { minimum: 5 } 
    validates :ship_date, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  
  # this method returns the quantity * unit_price_in_cents
  # unless either value is nil. If either is nil, it returns 0
  def line_price_in_cents
    if unit_price_in_cents == nil || quantity  == nil
      return 0 
    else
      quantity * unit_price_in_cents
    end
  end
end

# unit_price = 0

# if unit_price_in_cents == nil
#    unit_price_in_cents = unit_price 
# else
#    unit_price_in_cents
# end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
   # attr_accessible :email, :password, :password_confirmation
    validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    private

        def current_user
          @current_user ||= User.find(session[:user_id]) if session[:user_id]
        end
        helper_method :current_user
        
        def authorize
          redirect_to login_url, alert: "Not authorized" if current_user.nil?
        end
    
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
        @customers = Customer.all
    end
    
    def new
        @customer = Customer.new
    end
   
    def find
        #https://stackoverflow.com/questions/15191240/rails-implementation-of-search-with-autocomplete
        #@customer = Customer.find(params[:email])
        #<input id="user_name" name="user[name]" type="search" />
        render plain: params[:customer_email].inspect 
        #param = params[:customer_email]
        #@customer = Customer.find(:all, :conditions => ['email LIKE ?', "%#{email}%"])
    end 
    
    def create
        @customer = Customer.new(customer_params)
 
        @customer.save
        redirect_to @customer
    end
    
    def update
       @customer = Customer.new(customer_params)
 
        if @customer.update(customer_params)
            redirect_to @customer
        else
            render 'edit'
        end
    end
    
    
    def edit
        @customer = Customer.find(params[:id])
    end
    
    def show
        @customer = Customer.find(params[:id])
    end
 
    private
      def customer_params
        params.require(:customer).permit(:email)
      end
    end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
 def create
    @order = Order.find(params[:order_id])
    @order_item = @order.order_items.create(order_item_params)
    redirect_to order_path(@order)
  end
 
  private
    def order_item_params
      params.require(:order_item).permit(:item_name, :item_description, :unit_price_in_cents, :quantity)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @orders = Order.all
    end
    
    def show
        @order = Order.find(params[:id])
    end
    
     def create
        #render plain: params[:order].inspect 
         
        @customer = Customer.find(params[:customer_id])
        @order = @customer.orders.create(order_params)
        redirect_to customer_path(@customer)
      end
 
    private
        def order_params
          params
            .require(:order)
            .permit(:street_address, :city, :state, :postal_code, :ship_date)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
    
    def create
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_url, notice: "Logged in!"
      else
        flash.now.alert = "Email or password is invalid"
        render "new"
      end
    end
    
    def destroy
      session[:user_id] = nil
      redirect_to root_url, notice: "Logged out!"
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
    
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url, notice: "Thank you for signing up!"
      else
        render "new"
      end
    end
    
    private
        def user_params
          params
            .require(:user)
            .permit(:email, :password, :password_confirmation)
        end
        
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<%= form_with model: @customer, local: true do |form| %>

<% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> prohibited
        this customer from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>
 
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/customers/edit.html.erb

<h2> Edit Customer No: <%= @customer.id %></h2>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb

<h1>Customers</h1>

<hr>
<%= link_to 'New Customer', new_customer_path %>
<hr>
<table>
  <tr>
    <th>Id</th>
    <th>Email</th>
    
  </tr>
 
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= customer.email %></td>
      <td><%= link_to 'Show', customer_path(customer) %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', '/' %>

app/views/customers/new.html.erb
<h2> New Customer</h2>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<h2> Customer No: <%= @customer.id %></h2>
<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<h3>Customer Orders</h3>
<% @customer.orders.each do |order| %>
   <p>
    <%= order.street_address %> |
    <%= order.city %> |
    <%= order.postal_code %> |
    <%= order.ship_date %>
   </p>
<% end %>
<hr>

<h3>Add an Order:</h3>
<%= form_with(model: [ @customer, @customer.orders.build ], local: true) do |form| %>
  

  <p>
    <%= form.label :street_address %><br>
    <%= form.text_field :street_address %>
  <br>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  <br>
    <%= form.label :state %><br>
    <%= form.text_field :state %>
  
  <br>
    <%= form.label :postal_code %><br>
    <%= form.number_field :postal_code %>
  <br>
    <%= form.label :ship_date %><br>
    <%= form.date_field :ship_date %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>


 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientOrders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <hr>
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
      <hr>
      
    <%= yield %>
  </body>
</html>

app/views/orders/_order_items.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price, Cents</th>
    <th>Quantity</th>
    <th>Item Total, Cents</th>
  </tr>
 
  <% items.each do |item| %>
    <tr>
      <td><%= item.item_name %></td>
      <td><%= item.item_description %></td>
      <td><%= item.unit_price_in_cents %></td>
      <td><%= item.quantity %></td>
      <td><%= item.quantity * item.unit_price_in_cents %></td>
    </tr>
  <% end %>
</table>

app/views/orders/edit.html.erb
<h3>Edit an Order:</h3>

<%= form_with(model:  @order, local: true) do |form| %>
  

  <p>
    <%= form.label :street_address %><br>
    <%= form.text_field :street_address %>
  <br>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  <br>
    <%= form.label :state %><br>
    <%= form.text_field :state %>
  <br>
  <br>
    <%= form.label :postal_code %><br>
    <%= form.number_field :postal_code %>
  <br>
    <%= form.label :ship_date %><br>
    <%= form.date_field :ship_date %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>
 
 
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
 <% if current_user %>
    <h1>All Orders of <%= current_user.email %></h1>
<% else %>
    <h1>All Orders</h1>          
<% end %>
 
<table>
  <tr>
    <th>Order Id</th>
    <th>Shiped on</th>
    <th>Customer Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.ship_date %></td>
      <td>
          <%= order.customer.email %> 
      </td>
      <td><%= link_to 'Go to customer', customer_path(order.customer) %></td>
      
      <td><%= link_to 'Show', [order] %></td>
      <td><%= link_to 'Edit', edit_order_path(order) %></td>
    </tr>
  <% end %>
</table>
<hr>
<h4> Total, $: <%= @totalOfOrders %></h4>


<%= link_to 'Back', '/' %>

app/views/orders/show.html.erb
<h2> Order No: <%= @order.id %></h2>
<h4>
    <%= @order.street_address %> |
    <%= @order.city %> |
    <%= @order.postal_code %> |
    <%= @order.ship_date %>
</h4>

<h3>Items in Order</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price, Cents</th>
    <th>Quantity</th>
    <th>Item Total, Cents</th>
  </tr>
 
  <% @order.order_items.each do |item| %>
    <tr>
      <td><%= item.item_name %></td>
      <td><%= item.item_description %></td>
      <td><%= item.unit_price_in_cents %></td>
      <td><%= item.quantity %></td>
      <td><%= item.line_price_in_cents %></td>
    </tr>
  <% end %>
</table>



<h3>Add an Order Item:</h3>

<%= form_with(model: [ @order, @order.order_items.build ], local: true) do |form| %>
  <p>
    <%= form.label :item_name %><br>
    <%= form.text_field :item_name %>
  </p>
  <p>
    <%= form.label :item_description %><br>
    <%= form.text_area :item_description %>
  </p>
  <p>
    <%= form.label :unit_price_in_cents %><br>
    <%= form.number_field :unit_price_in_cents %>
  </p>
  
  <p>
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

<hr>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>


 

app/views/users/new.html.erb

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
                                                                                                                     
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>


app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<hr>
<%= form_with(url: "/find", method: "post") do %>
  <p>
    <%= label_tag( :email, 'Search Customer by email') %>
    <%= search_field(:customer, :email) %>
    <%= submit_tag("Search") %>
  </p>
<% end %>

<hr>
| <%= link_to 'Orders', controller: 'orders' %> | <%= link_to 'Customers', controller: 'customers' %> |
<hr>